-- PostgreSQL schema for Migratabase.
-- Note: creating the database itself is intentionally excluded; create it externally,
-- then point DATABASE_URL at it (see .env.example).

-- Table for migrants with all relevant information
CREATE TABLE IF NOT EXISTS migrants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  country_of_origin VARCHAR(255) NOT NULL,
  date_of_birth DATE NOT NULL,
  age INTEGER,
  current_location VARCHAR(255),
  status VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_migrants_name ON migrants (name);
CREATE INDEX IF NOT EXISTS idx_migrants_country ON migrants (country_of_origin);
CREATE INDEX IF NOT EXISTS idx_migrants_status ON migrants (status);

-- Table for just names (normalized)
CREATE TABLE IF NOT EXISTS migrant_names (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  migrant_id INTEGER NOT NULL REFERENCES migrants(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_migrant_names_migrant_id ON migrant_names (migrant_id);
CREATE INDEX IF NOT EXISTS idx_migrant_names_name ON migrant_names (name);

-- Table for relationships between migrants
CREATE TABLE IF NOT EXISTS migrant_relationships (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  migrant_id_1 INTEGER NOT NULL REFERENCES migrants(id) ON DELETE CASCADE,
  migrant_id_2 INTEGER NOT NULL REFERENCES migrants(id) ON DELETE CASCADE,
  relationship_type VARCHAR(100) NOT NULL, -- e.g., 'family', 'friend', 'acquaintance', 'colleague'
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT unique_relationship UNIQUE (migrant_id_1, migrant_id_2, relationship_type)
);

CREATE INDEX IF NOT EXISTS idx_migrant_relationships_migrant_1 ON migrant_relationships (migrant_id_1);
CREATE INDEX IF NOT EXISTS idx_migrant_relationships_migrant_2 ON migrant_relationships (migrant_id_2);
